name: test
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch nano $REF_VERSION
        run: |
          git fetch --tags
          REF_VERSION=$(git tag --list | tail -n 1)
          echo "REF_VERSION: $REF_VERSION"
          git clone --depth 1 --branch $REF_VERSION git://git.savannah.gnu.org/nano.git

      - name: Setup and configure nano
        run: |
          cd nano
          sudo apt-get install -y autoconf automake autopoint gcc gettext git groff make pkg-config texinfo libncurses5-dev
          ./autogen.sh
          ./configure --prefix=/usr
          cd -

      - name: Build nano
        run: |
          cd nano
          make -j && sudo make install
          cd -
          nano/src/nano --version

      - name: Test nanorc
        run: |
          cat README.md | sed -n '0,/```/d;p' | sed '/```/Q' > .nanorc
          TERM=xterm timeout 1s nano/src/nano --rcfile .nanorc >/dev/null 2>error.txt || true
          cat error.txt | grep -v -e "Received SIGHUP or SIGTERM" -e "Too many errors from stdin" && false
          echo "All seems good!"
